name: EiTo
favicon: null
layout_spectrum: 0.01364
typography_spectrum: 1
title: 'Berater | Unternehmer | Tr√§umer'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3f4545'
    - '#adafb0'
    - '#a2a5a5'
    - '#8b8d8e'
  brandStrength: 1
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 1
purpose: []
