name: EiTo
favicon: null
layout_spectrum: 0.3924508369527757
typography_spectrum: 0.28290549316443503
title: 'Berater | Unternehmer | Tr√§umer'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.5036597549915314
  lightness: 0.21777462330646813
  saturation: 0.5144569310359657
  rhythmicContrast: 0.6069047430064529
purpose: []
